global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "llm-api"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "llm-api-container:8000"
